<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Company name</a>
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="">Home</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <form action="/index/signout" method="POST">
        <button class="btn btn-dark" type="submit" name="signout">Sign out</button>
      </form>
    </div>
  </div>
</header>
<span>Current Date and Time - <b class="text-success"><?php echo $time; ?></b></span>